# keep-sorted start
- id: cargo-check
  name: Run `cargo check`
  language: system
  types: [rust]
  entry: cargo check
  pass_filenames: false
- id: cargo-clippy
  name: Run `cargo clippy`
  language: system
  types: [rust]
  entry: cargo clippy
  args: ["--", "--deny", "warnings"]
  pass_filenames: false
- id: cargo-fmt
  name: Run `cargo fmt`
  language: system
  types: [rust]
  entry: cargo fmt
  args: ["--"]
- id: cargo-llvm-cov
  name: Run `cargo llvm-cov`
  language: system
  types: [rust]
  entry: cargo llvm-cov test
  args: ['--quiet']
  pass_filenames: false
- id: cargo-test
  name: Run `cargo test`
  language: system
  types: [rust]
  entry: cargo test
  args: []
  pass_filenames: false
# keep-sorted end
